version: 2.1

executors:
  my-executor:
    docker:
      - image: node:10

jobs:
  go:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps
      - run:
          name: 'Install dependencies'
          command: npm ci
      - run:
          name: 'Generate it'
          command: npm run generate
      - run:
          name: 'Build it'
          command: npm run build
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v2-deps-{{ checksum "package-lock.json" }}
      - run:
          name: 'Deploy'
          command: npm run firebase:deploy:ci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - go
